name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          TARGET_REPO: AY-Front/blogs
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://www.ay-site.com
          COMMIT_MESSAGE: Auto deploy by the Vuepress-deploy
